### ISSUE TITLE
Can't find babel-loader

### ISSUE THREAD

**Issue by Yamakaky** [Olical/bastion#3]
bastion searches modules in it's own node_modules. It's incorrect with npm3 https://docs.npmjs.com/how-npm-works/npm3.

**Comment by Yamakaky** [comment]
I solved it by creating a symlink.

**Comment by Olical** [comment]
Ah, I see, thanks for the report. I've had a few issues with referencing node modules, I expected some bugs around this area. I wonder if there's an API I can call to get the path to it. It's a shame npm@2 and npm@3 behave so differently.

**Comment by Yamakaky** [comment]
I think it's because Windows handles badly long file paths ;)

**Comment by Olical** [comment]
Probably an npm@2 / npm@3 issue mainly. May look into it some day. If you want to fork the project and try it out, go ahead.
