### ISSUE TITLE
Static files management

### ISSUE THREAD

**Issue by Yamakaky** [Olical/bastion#5]
How do you manage static files? I thought `dist/` was only for generated files.

**Comment by Olical** [comment]
What do you mean by static files? For a web server or something?

**Comment by Yamakaky** [comment]
For example on my project, the `bundle.js` is generated but `index.html` is hand-written.

**Comment by Olical** [comment]
You can ignore the `dist` directory in git but still `git add dist/index.html`. It's pretty clever like that :smile:
